# Generated by Django 5.2.7 on 2025-10-17 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_delete_productgallery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='bundle_items',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_bundle',
        ),
    ]
